### PR TITLE
Modified code of User program in the CopyTool as discussed in the meeting

### PR DESCRIPTION
**Pull request by SandeepNayak077**
1) Added serialize and de-serialize method  
2) Added a class 'CopyInformationParameterValue' to handle serialization and de-serialization
3) Modified the code of UserScreen to register copy job and to abort the copy process

### CODE REVIEW

**Comment by daisukenishino** [comment]
Divides the feature branch for every problem, Please send two PullRequest.
Please check the following CONTRIBUTING.md.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/CONTRIBUTING.md

**Comment by daisukenishino** [comment]
I mistook description of the reason for the Close.
The following is the correct Close the reason.

Because Specification_EN.xlsx has been rolled back.
Therefor,The re-pull the OpenTouryoProject/CloudOS and,
please run the Push and PullRequest again.

**Comment by kishoreandukuri** [comment]
Dear Nishinio-san,
Please confirm the below
>>Divides the feature branch for every problem, Please send two PullRequest.
<HODC Understanding>No need to create feature branch for CopyTool.

>>Therefor,The re-pull the OpenTouryoProject/CloudOS and,
>>please run the Push and PullRequest again.
<HODC Undertsanding>Again HODC creates new pull request and send it to Nishino-san or Reopen the pull request.

Thanks and Regards,

**Comment by daisukenishino** [comment]
>>Again HODC creates new pull request and send it to Nishino-san or Reopen the pull request.

Thank you.

Digression:
If you use a string that can be regarded as XML tags, the string does not appear correctly on Github.
For example, the above "HODC Undertsanding" does not appear.

**Comment by kishoreandukuri** [comment]
Thank you for the reply.
/// <summary>>>
sure

**Comment by daisukenishino** [comment]
I checked the pullrequest that was re-opened.
However, are included as usual Specification_EN.xlsx.
This can not be merged. Please create a new pullrequest.

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,
HODC re pulled from OpenTouryoProjects repository,  pushed the chages and created pull request.

[CreatedPullRequest](https://github.com/SymphonyTeleca/CloudOS/pull/7)

please review

**Pull request closed without merging**
