### PR TITLE
Re-pulled from OpenTouryoProject repositiry as per comments 

### PR DESCRIPTION
**Pull request by kishoreandukuri**

### CODE REVIEW

**Comment by daisukenishino** [comment]
I have found a one mistake.
"Into-branch" of the target is set to the "master-branch" rather than "nishino-branch".

**Comment by SandeepNayak077** [comment]
\>>I have found a one mistake.
\>>"Into-branch" of the target is set to the "master-branch" rather than "nishino-branch".

Do HODC needs to create pull request again?

Please confirm.

**Comment by daisukenishino** [comment]
There is no need to send a pull request again.
Be careful next time.

**Comment by SandeepNayak077** [comment]
Sorry for the inconvience Nishino-san
HODC will take care in the future.

**Comment by SandeepNayak077** [comment]
HODC is requesting Nishino-san to confirm the code changes of CopyTool and AsyncProcessingService project

Did the code changes meet the Nishino-san's expectations ?

Please confirm.

**Comment by daisukenishino** [comment]
I have not been able to confirm details of the code because there is no time.
Please ask at the meeting if you have any questions.

**Comment by SandeepNayak077** [comment]
Dear Nishino-san, 
No problem, we can understand.

From HODC there is no more questions, but HODC only want to confirm the coding.
- Did HODC implemented correct or not.
- Did HODC meet the Nishino-san's expectation or not.

HODC is requesting to test the CopyTool and AsyncProcessingService in Azure VM by HISOL.
If the HISOL test result is success, then HODC thinks the current implementation is correct and it meets the Nishino-san's expectation. 

Once Nishino-san confirms, HODC will start code cleanup.

Now, HODC will work on code modification of SPA_WebAPI_EF application

Please let us know.

**Comment by daisukenishino** [comment]
- We have completed the preparation perform the test.  
Check list has been created.
- If your development has been completed,  
Do you also test by creating a checklist?
- If the test has been completed,  
please tell us the VM that we can use for testing.

**Comment by SandeepNayak077** [comment]
Yes HODC has already tested in VM. 

HODC has already shared VM credentials in yesterday's mail (subject: 'Today's Delivery (22-Apr-2015)').

Now, HODC will resend the VM credential information

**Comment by SandeepNayak077** [comment]
Dear Nishino-san,

HODC has shared the VM credentials through mail.
Subject of the mail: "VM Credentials for testing CopyTool and AsyncProcessingService"

please confirm.

**Pull request merged**
